# Generated by Django 4.2.7 on 2024-09-22 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='code',
            field=models.CharField(blank=True, default='RUS-1727', null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 22, 14, 12, 39, 837210, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 14, 12, 39, 837140, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='from_airport',
            field=models.CharField(blank=True, default='Домодедово', null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='to_airport',
            field=models.CharField(blank=True, default='Астрахань', null=True),
        ),
    ]
