# Generated by Django 4.2.7 on 2024-09-22 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_flight_code_alter_flight_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 22, 14, 13, 15, 450714, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 14, 13, 15, 450643, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
