# Generated by Django 4.2.7 on 2024-09-25 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_flight_date_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 25, 11, 46, 29, 416492, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 11, 46, 29, 416416, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
