# Generated by Django 4.2.7 on 2025-02-11 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_flight_qr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="qr",
        ),
    ]
